### ISSUE TITLE
jawa - integrasi MIT license dengan translate bahasa jawa request: `None`

### ISSUE THREAD

**Issue by slowy07** [dapuntech/phantom#2]
integrasi MIT license dengan translate bahasa jawa

**Comment by IlhamSuandi** [comment]
@slowy07 ini berarti buat file baru ya bang?

**Comment by slowy07** [comment]
iyaa buat file baru aj @IlhamSuandi, yang pr nomor #6 dah bener 💯

**Comment by slowy07** [comment]
issue closed cause pull reqest are merged
